linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default: false
  new-from-rev: HEAD~1

linters:
  enable:
    - errcheck
  disable:
    - unused
  # add or remove linters as needed

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
