package main

const STORAGE_BUCKET = "postmanpat"

const TF_VAR_PREFIX = "TF_VAR_"
const DIGITALOCEAN_BUCKET_ACCESS_KEY = "DIGITALOCEAN_BUCKET_ACCESS_KEY"
const DIGITALOCEAN_BUCKET_SECRET_KEY = "DIGITALOCEAN_BUCKET_SECRET_KEY"
const IMAP_URL = "IMAP_URL"
const IMAP_USER = "IMAP_USER"
const IMAP_PASS = "IMAP_PASS"
